name: Build
on: [push]
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: make build
      - name: Unit Test
        run: make unit-test
